services:
  - type: web
    name: tartib-backend
    env: node
    plan: free
    rootDir: Tartib_backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://tartib.vercel.app
      - key: postgresql://neondb_owner:npg_E3cHJa7wVOit@ep-proud-poetry-aslotw3l-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
        sync: false
      - key: AQ.Ab8RN6LRb5zY2h6XAZPcNdS583rtZtb00qzk4bBnXTeGymWMPg
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
