import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Bot, CheckCircle2, Circle, Clock3, Plus, Target, Trash2 } from 'lucide-react';
import { api } from '../../utils/api';
import './style.css';

const emptyForm = { title: '', description: '', reason: '', start_date: new Date().toISOString().slice(0, 10), deadline: '', current_state: '', target_state: '', daily_minutes: 60, weekly_days: 5 };

function Progress({ value = 0 }) {
  return <div className="goal-progress"><span style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>;
}

function GoalForm({ onClose, onCreated }) {
  const [form, setForm] = useState(emptyForm);
  const [step, setStep] = useState(1);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const next = () => { if (step === 1 && !form.title.trim()) return setError('Maqsad nomini kiriting.'); if (step === 2 && (!form.deadline || form.start_date > form.deadline)) return setError('Tugash sanasini to‘g‘ri tanlang.'); setError(''); setStep(value => Math.min(6, value + 1)); };
  const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { const goal = await api.addGoal({ ...form, daily_minutes: Number(form.daily_minutes), weekly_days: Number(form.weekly_days) }); onCreated(goal); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const renderStep = () => {
    if (step === 1) return <><label>Maqsadingiz nima?<input autoFocus required value={form.title} onChange={event => update('title', event.target.value)} placeholder="Masalan: 3 oyda IELTS 6.5 olish" /></label><label>Bu nima uchun muhim?<textarea value={form.reason} onChange={event => update('reason', event.target.value)} placeholder="Ixtiyoriy" /></label></>;
    if (step === 2) return <><label>Boshlanish sanasi<input type="date" value={form.start_date} onChange={event => update('start_date', event.target.value)} /></label><label>Qachongacha erishmoqchisiz?<input required type="date" value={form.deadline} onChange={event => update('deadline', event.target.value)} /></label></>;
    if (step === 3) return <label>Hozirgi holatingiz qanday?<textarea autoFocus value={form.current_state} onChange={event => update('current_state', event.target.value)} placeholder="Masalan: Hozir IELTS darajam 5.0" /></label>;
    if (step === 4) return <label>Qanday natijaga erishmoqchisiz?<textarea autoFocus value={form.target_state} onChange={event => update('target_state', event.target.value)} placeholder="Masalan: IELTS 6.5" /></label>;
    if (step === 5) return <><label>Kuniga qancha vaqt ajrata olasiz?<select value={form.daily_minutes} onChange={event => update('daily_minutes', event.target.value)}><option value="30">30 daqiqa</option><option value="60">1 soat</option><option value="90">1.5 soat</option><option value="120">2 soat</option><option value="180">3 soat</option><option value="240">4+ soat</option></select></label><p className="wizard-hint">AI reja hech qachon bu limitdan oshmaydi.</p></>;
    return <><label>Haftada necha kun ishlaysiz?<select value={form.weekly_days} onChange={event => update('weekly_days', event.target.value)}><option value="7">Har kuni</option><option value="6">Haftada 6 kun</option><option value="5">Haftada 5 kun</option><option value="3">Haftada 3 kun</option></select></label><label>Maqsad haqida<textarea value={form.description} onChange={event => update('description', event.target.value)} placeholder="Qo‘shimcha ma’lumot" /></label></>;
  };
  return <div className="goal-modal-backdrop" onMouseDown={onClose}><form className="goal-modal" onSubmit={submit} onMouseDown={event => event.stopPropagation()}><div className="goal-modal-head"><div><span className="eyebrow">TARTIB / AI PLANNER</span><h2>Yangi maqsad</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><div className="wizard-progress">{[1, 2, 3, 4, 5, 6].map(item => <span className={item <= step ? 'active' : ''} key={item} />)}</div><p className="wizard-step">{step} / 6</p>{error && <p className="goal-error">{error}</p>}{renderStep()}<div className="wizard-actions">{step > 1 && <button type="button" className="goal-secondary" onClick={() => { setError(''); setStep(value => value - 1); }}>Orqaga</button>}{step < 6 ? <button type="button" className="goal-primary" onClick={next}>Davom etish <ArrowRight size={16} /></button> : <button className="goal-primary" disabled={busy}>{busy ? 'AI reja tayyorlamoqda...' : <><Bot size={17} /> AI bilan boshlash</>}</button>}</div></form></div>;
}

function GoalDetail({ goalId, onBack }) {
  const [goal, setGoal] = useState(null); const [plan, setPlan] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = () => api.getGoal(goalId).then(setGoal).catch(err => setError(err.message));
  useEffect(() => { load(); }, [goalId]);
  const planDay = async () => { setBusy(true); setError(''); try { setPlan(await api.planGoalDay(goalId, { replace: Boolean(plan) })); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const confirmPlan = async () => { if (!plan?.id) return; setBusy(true); setError(''); try { await api.confirmGoalDay(goalId, plan.id); setPlan(null); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const toggleTask = async task => { try { await api.updateTask(task.id, { completed: !task.completed }); await load(); } catch (err) { setError(err.message); } };
  if (!goal) return <div className="page-container"><button className="back-button" onClick={onBack}><ArrowLeft size={16} /> Orqaga</button><p className="goal-error">{error || 'Yuklanmoqda...'}</p></div>;
  if (plan) return <div className="page-container goals-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} /> Maqsadlar</button><div className="goal-panel plan-preview"><span className="eyebrow">AI DAILY PLAN</span><div className="panel-title"><h1 className="page-title">Bugungi reja</h1><b>{plan.planned_minutes} / {plan.available_minutes} min</b></div><p className="plan-summary">{plan.summary || 'Bugungi asosiy fokus maqsadingizga moslashtirildi.'}</p>{plan.tasks.map((task, index) => <div className="preview-task" key={`${task.text}-${index}`}><span>{index + 1}</span><div><b>{task.text}</b><small>{task.duration_minutes} min · {task.priority}</small></div></div>)}<div className="plan-actions"><button className="goal-secondary" onClick={planDay} disabled={busy}>Qayta tuzish</button><button className="goal-primary" onClick={confirmPlan} disabled={busy}><CheckCircle2 size={16} /> Rejani tasdiqlash</button></div></div></div>;
  const remaining = goal.deadline ? Math.max(0, Math.ceil((new Date(`${goal.deadline}T23:59:59`) - new Date()) / 86400000)) : null;
  return <div className="page-container goals-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} /> Maqsadlar</button><header className="goal-detail-header"><div><span className="eyebrow">ACTIVE GOAL</span><h1 className="page-title">{goal.title}</h1><p className="page-subtitle">{goal.description || goal.target_state}</p></div><div className="goal-score">{goal.progress}%<small>progress</small></div></header>{error && <p className="goal-error">{error}</p>}<section className="goal-detail-stats"><div><Clock3 size={16} /><b>{remaining ?? '-'} kun</b><small>qoldi</small></div><div><CheckCircle2 size={16} /><b>{goal.tasks.filter(task => task.completed).length}/{goal.tasks.length}</b><small>task bajarildi</small></div><div><Target size={16} /><b>{goal.milestones.length}</b><small>milestone</small></div></section><section className="goal-detail-layout"><div className="goal-panel"><div className="panel-title"><h2>Roadmap</h2><span>{goal.progress}%</span></div><Progress value={goal.progress} /><div className="milestone-list">{goal.milestones.map((milestone, index) => <div className="milestone" key={milestone.id}><span className={milestone.status === 'completed' ? 'milestone-dot done' : 'milestone-dot'}>{milestone.status === 'completed' ? '✓' : index + 1}</span><div><b>{milestone.title}</b><p>{milestone.description}</p></div></div>)}</div></div><div className="goal-panel"><div className="panel-title"><h2>Bugungi reja</h2><button className="goal-secondary" onClick={planDay} disabled={busy}><Bot size={15} /> {busy ? 'Tuzilmoqda...' : 'AI reja'}</button></div>{goal.tasks.filter(task => task.due_date === new Date().toISOString().slice(0, 10)).map(task => <button className={`goal-task ${task.completed ? 'done' : ''}`} key={task.id} onClick={() => toggleTask(task)}>{task.completed ? <CheckCircle2 size={18} /> : <Circle size={18} />}<span>{task.text}<small>{task.priority} · {task.start_time || 'Bugun'}</small></span></button>)}{!goal.tasks.some(task => task.due_date === new Date().toISOString().slice(0, 10)) && <p className="empty-goal">AI siz uchun bugungi rejani tuzadi.</p>}</div></section></div>;
}

export default function Goals({ onBack }) {
  const [goals, setGoals] = useState([]); const [selected, setSelected] = useState(null); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const load = () => api.getGoals().then(setGoals).catch(err => setError(err.message));
  useEffect(() => { load(); }, []);
  if (selected) return <GoalDetail goalId={selected} onBack={() => { setSelected(null); load(); }} />;
  const active = goals.filter(goal => goal.status === 'active');
  return <div className="page-container goals-page"><div className="page-header goals-heading"><div><span className="eyebrow">PERSONAL DIRECTION</span><h1 className="page-title">Maqsadlar</h1><p className="page-subtitle">Katta niyatlarni aniq qadamlarga aylantiring.</p></div><button className="goal-primary" onClick={() => setShowForm(true)}><Plus size={17} /> Yangi maqsad</button></div>{error && <p className="goal-error">{error}</p>}{active.length === 0 && <div className="empty-goals"><Target size={32} /><h2>Birinchi maqsadingizni belgilang</h2><p>AI yo'l xaritasi va kunlik rejani keyinroq yaratishga yordam beradi.</p></div>}<div className="goals-grid">{goals.map(goal => <button className="goal-card" key={goal.id} onClick={() => setSelected(goal.id)}><div className="goal-card-top"><span className="goal-status">{goal.status}</span><span>{goal.progress || 0}%</span></div><h2>{goal.title}</h2><p>{goal.description || goal.target_state || 'Maqsad tafsilotlari'}</p><Progress value={goal.progress} /><div className="goal-card-meta"><span>{goal.current_milestone || 'Roadmap tayyorlanmoqda'}</span><span>{goal.deadline || 'Muddat belgilanmagan'}</span></div></button>)}</div>{showForm && <GoalForm onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); load(); }} />}</div>;
}
